### ISSUE TITLE
Set Up Game Structure and Deck Handling

### ISSUE THREAD

**Issue by ginsta6** [ginsta6/war_cardgame#2]
Set up the basic game structure and deck handling, including functionality to shuffle the deck and deal cards.

### Tasks
- [x] Create Card and Deck classes
- [x] Handle deck creation based on user input: full deck or high cards only (9s and up)
- [x] Add shuffle() method
- [x] Add deal() method
