### ISSUE TITLE
Implement Card Comparison and Round Logic

### ISSUE THREAD

**Issue by ginsta6** [ginsta6/war_cardgame#3]
Implement the logic for a single round of the game, including comparing player and CPU cards.

### Tasks
- [x] Implement card comparison
- [x] Implement "war" logic when both players play an equal card
- [x] Implement logic to determine the winner of each round
- [x] Implement adding and removing from decks based on outcome of round
