### ISSUE TITLE
Game End Logic and Congratulatory Message

### ISSUE THREAD

**Issue by ginsta6** [ginsta6/war_cardgame#6]
Implement the logic to end the game and display a congratulatory message when the game ends.

### Tasks
- [x] Implement game end clause
- [x] Implement UI message for game end
- [ ] Program asks for user input after game and in order to play again
